spring.application.name=teamflow-backend

spring.datasource.url=jdbc:postgresql://localhost:5433/teamflow
spring.datasource.username=teamflow
spring.datasource.password=dev_only_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

app.jwt.secret=${JWT_SECRET:dev-only-insecure-default-secret-key-please-change-in-real-environments-1234567890}
app.jwt.expiration-minutes=60

management.endpoints.web.exposure.include=health,prometheus
management.prometheus.metrics.export.enabled=true
logging.level.org.springframework.security=DEBUG
